# Generated by Django 4.2.11 on 2024-09-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='contenido',
            new_name='descripcion',
        ),
    ]
